### ISSUE TITLE
General software version and active software version can go out of sync

### ISSUE THREAD

**Issue by jamesjwei** [kstaniek/condoor-ng#1]
Steps to produce:

(1) Use CSM to upgrade eXR to version A.
(2) Login to the device and manually upgrade eXR to version B.
(3) Use CSM to retrieve latest inventory. Now the General Software version remains as A while the active software version becomes B.

**Comment by kstaniek** [comment]
This is potentially an issue in csmpe or csm. Retrieving latest inventory should always connect to the device with force_rediscovery=True.

**Comment by jamesjwei** [comment]
+Alex
